version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6


workflows: 
  test-deploy:
    jobs:
      - test

workflows: 
  version: 2
  commit-workflow: 
    jobs:
      - test
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
   
      
jobs:
  build:
    docker:
      - image: cimg/node:14.13.0
    steps: 
      - checkout
      - run:
          name: Running test
          command: echo "build"
  test:
    docker:
      - image: cimg/node:14.13.0
    steps: 
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Running test
          command: npm run test


