version: 2.1

workflows: 
  version: 2
  # commit-workflow: 
  #   jobs:
  #     - test
  schedule-workflow:
    triggers:
      - schedule:
          cron: "* * * * *"
    jobs:
      - test
   
      
jobs:
  build:
    docker:
      - image: cimg/node:14.13.0
    steps: 
      - checkout
      - run:
          name: Running test
          command: echo "build"
  test:
    docker:
      - image: cimg/node:14.13.0
    steps: 
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Running test
          command: npm run test


