version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6


workflows: 
  test-deploy:
    jobs:
      - test
      
jobs:
  test:
    docker:
      - image: cimg/node:17.2.0
    steps: 
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Running test
          command: npm run test
   
